# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proveService.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12proveService.proto\x12\x0cproveService\"\xa9\x01\n\x04Task\x12\x14\n\x0c\x63urrent_root\x18\x01 \x01(\t\x12\x15\n\rcurrent_width\x18\x02 \x01(\x05\x12\x16\n\x0e\x63urrent_peaksx\x18\x03 \x03(\t\x12\x16\n\x0e\x63urrent_peaksy\x18\x04 \x03(\t\x12\x18\n\x10items_to_updatex\x18\x05 \x03(\t\x12\x18\n\x10items_to_updatey\x18\x06 \x03(\t\x12\x10\n\x08new_root\x18\x07 \x01(\t\" \n\x0eProvedResponse\x12\x0e\n\x06Status\x18\x01 \x01(\t2I\n\nProverNode\x12;\n\x07\x45xecute\x12\x12.proveService.Task\x1a\x1c.proveService.ProvedResponseb\x06proto3')



_TASK = DESCRIPTOR.message_types_by_name['Task']
_PROVEDRESPONSE = DESCRIPTOR.message_types_by_name['ProvedResponse']
Task = _reflection.GeneratedProtocolMessageType('Task', (_message.Message,), {
  'DESCRIPTOR' : _TASK,
  '__module__' : 'proveService_pb2'
  # @@protoc_insertion_point(class_scope:proveService.Task)
  })
_sym_db.RegisterMessage(Task)

ProvedResponse = _reflection.GeneratedProtocolMessageType('ProvedResponse', (_message.Message,), {
  'DESCRIPTOR' : _PROVEDRESPONSE,
  '__module__' : 'proveService_pb2'
  # @@protoc_insertion_point(class_scope:proveService.ProvedResponse)
  })
_sym_db.RegisterMessage(ProvedResponse)

_PROVERNODE = DESCRIPTOR.services_by_name['ProverNode']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TASK._serialized_start=37
  _TASK._serialized_end=206
  _PROVEDRESPONSE._serialized_start=208
  _PROVEDRESPONSE._serialized_end=240
  _PROVERNODE._serialized_start=242
  _PROVERNODE._serialized_end=315
# @@protoc_insertion_point(module_scope)
